### ISSUE TITLE
serve.js is missing

### ISSUE THREAD

**Issue by nsantini** [evbogue/minbase#3]
Hi, I just did a fresh clone (from github) and followed the instructions.
`npm start` fails with `Error: Cannot find module serve.js`

**Comment by evbogue** [comment]
I've been using minbase as a dependency for so long, I forgot starting it on it's own doesn't work anymore. I'm going to fix this asap.

In the meantime you can use http://github.com/evbogue/decent -- that'll using minbase as a node module, and it starts right now

To run the main ssb network using decent use

```
npm start -- --appname=ssb
```

**Comment by nsantini** [comment]
using Decent works, thanks for your quick reply

**Comment by evbogue** [comment]
Fixed in fa990c3c1bb26fac488d0440f044528ac4319647
